# Generated by Django 4.0.1 on 2022-03-07 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
